/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eztcn_user_hall_utils_CheckSignUtils */

#ifndef _Included_com_eztcn_user_hall_utils_CheckSignUtils
#define _Included_com_eztcn_user_hall_utils_CheckSignUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eztcn_user_hall_utils_CheckSignUtils
 * Method:    getSign
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eztcn_user_hall_utils_CheckSignUtils_getSign
  (JNIEnv *, jclass, jstring, jobjectArray, jobject);

/*
 * Class:     com_eztcn_user_hall_utils_CheckSignUtils
 * Method:    getAppId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eztcn_user_hall_utils_CheckSignUtils_getAppId
  (JNIEnv *, jclass);

/*
 * Class:     com_eztcn_user_hall_utils_CheckSignUtils
 * Method:    MD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eztcn_user_hall_utils_CheckSignUtils_MD5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
